# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('county', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
