# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0003_auto_20170908_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
