# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0004_auto_20170909_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
